doctrine_migrations:
    dir_name: "%kernel.root_dir%/../vendor/inkstudio/beaver/CoreBundle/Distribution/Migrations"
    namespace: Application\Migrations
    table_name: beaver_migration_versions
    name: Application Migrations
    organize_migrations: false # Version >= 1.2, possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    custom_template: ~ # Version >= 1.2, path to your custom migrations template

doctrine:
    dbal:
        schema_filter: ~^(beaver_)~