imports:
    - { resource: '@BackendBundle/Resources/config/services.yml' }
    - { resource: '@CoreBundle/Resources/config/services.yml' }

#beaver:
#    layouts:  '%page.layouts%'
#    contents: '%contents%'
#    blocks:   '%beaver_blocks_directory%'
