<?php
namespace Beaver\BackendBundle;

use Beaver\BackendBundle\DependencyInjection\BeaverBackendExtension;
use Beaver\BackendBundle\DependencyInjection\Compiler\MenuPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

/**
 * Class BackendBundle
 *
 * @package Beaver\BackendBundle
 */
class BackendBundle extends Bundle
{
    const BUNDLE = '@Backend';

    /**
     * @param ContainerBuilder $container
     */
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub

        $container->addCompilerPass(new MenuPass());
    }

    /**
     * @return BeaverBackendExtension|null|\Symfony\Component\DependencyInjection\Extension\ExtensionInterface
     */
    public function getContainerExtension()
    {
        return new BeaverBackendExtension();
    }
}
