<?php
/**
 * Created by PhpStorm.
 * User: leonardojsuarez
 * Date: 12/03/2018
 * Time: 22:16
 */

namespace Beaver\ContentBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class GalleryType
 *
 * @package Beaver\ContentBundle\Form
 */
class GalleryType extends AbstractType
{
	public function getParent()
	{
		return HiddenType::class;
	}
	
	public function buildView(FormView $view, FormInterface $form, array $options)
	{
		parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
	}
	
	public function configureOptions(OptionsResolver $resolver)
	{
		parent::configureOptions($resolver); // TODO: Change the autogenerated stub
	}
}
